name: truvari
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - truvari
  - tabix
  - bcftools
  - samtools
  - bedtools
  - google-cloud-sdk
  - snakemake
prefix: /opt/conda/envs/truvari
